apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-cinder-csi
  namespace: argocd
spec:
  project: infra-apps
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: openstack-cinder-csi/prod
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openstack-cinder-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
