---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: argocd

resources:
  - https://install.portworx.com/2.13?comp=pxoperator&kbver=1.25.7&ns=portworx
