apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: kyverno
  namespace: kyverno
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno/
  valuesFile: values.yaml
  version: 2.7.3

resources:
- https://raw.githubusercontent.com/kyverno/policies/main/pod-security/subrule/podsecurity-subrule-baseline/podsecurity-subrule-baseline.yaml
- https://raw.githubusercontent.com/kyverno/policies/main/pod-security/subrule/restricted/restricted-latest/restricted-latest.yaml

patches:
- path: kustomizations/crd_policies.yaml
- path: kustomizations/crd_clusterpolicies.yaml
