mailu:
  hostnames:
    - mail.sh4ke.rocks
    - sh4ke.rocks

  domain: sh4ke.rocks

  secretKey: <secret_key>

  initialAccount:
    username: admin
    domain: sh4ke.rocks
    password: <initial_admin_password>

  database:
    type: mysql
    roundcubeType: mysql

    mysql:
      rootPassword: <mysql_root_password>

      database: mailu
      user: mailu
      password: <mysql_password>

      roundcubeDatabase: roundcube
      roundcubeUser: roundcube
      roundcubePassword: <roundcube_password>

  certmanager:
    issuerName: letsencrypt-prod

  ingress:
    tlsFlavor: cert
    annotations:
      kubernetes.io/ingress.class: "nginx"

  front:
#    hostPort:
#      enabled: false

    externalService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 213.95.155.192

  persistence:
    single_pvc: false

  admin:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  redis:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  postfix:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  dovecot:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  rspamd:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  clamav:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  roundcube:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  webdav:
    enabled: true
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"

  mysql:
    persistence:
      size: 1Gi
      storageClass: "csi-cinder-sc-delete-all-zones"
