mailu:
  hostnames:
    - mail.ws.sh4ke.rocks

  domain: ws.sh4ke.rocks

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - k3s-server-1

  secretKey: <path:kv/data/k3s/argocd/mailu#secret_key>

  initialAccount:
    username: admin
    domain: ws.sh4ke.rocks
    password: <path:kv/data/k3s/argocd/mailu#initial_admin_password>

  persistence:
    single_pvc: false

  global:
    database:
      roundcube:
        password: <path:kv/data/k3s/argocd/mailu#roundcube_password>

  postgresql:
    enabled: true
    auth:
      postgresPassword: <path:kv/data/k3s/argocd/mailu#postgresPassword>
      password: <path:kv/data/k3s/argocd/mailu#postgresUserPassword>
    primary:
      persistance:
        enabled: true
        storageClass: longhorn
        size: 1Gi

  ingress:
    # tlsFlavorOverride: cert
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  front:
    hostPort:
      enabled: false
    externalService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 31.172.117.18

  admin:
    persistence:
      size: 1Gi
      storageClass: longhorn

  redis:
    master:
      persistence:
        size: 1Gi
        storageClass: longhorn

  postfix:
    image:
      repository: docker.io/sh4ke/mailu-postfix
      tag: 2.0
    persistence:
      size: 1Gi
      storageClass: longhorn

  dovecot:
    persistence:
      size: 1Gi
      storageClass: longhorn

  rspamd:
    persistence:
      size: 1Gi
      storageClass: longhorn

  clamav:
    persistence:
      size: 1Gi
      storageClass: longhorn

  webmail:
    persistence:
      size: 1Gi
      storageClass: longhorn

  webdav:
    enabled: true
    persistence:
      size: 1Gi
      storageClass: longhorn
