mailu:
  mailuVersion: 1.9
  hostnames:
    - mail.ws.sh4ke.rocks

  domain: ws.sh4ke.rocks
  subnet: ""

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - k3s-server-1
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mailu
        topologyKey: kubernetes.io/hostname

  secretKey: <path:kv/data/k3s/argocd/mailu#secret_key>

  initialAccount:
    username: admin
    domain: ws.sh4ke.rocks
    password: <path:kv/data/k3s/argocd/mailu#initial_admin_password>

  database:
    type: mysql
    roundcubeType: mysql

    mysql:
      rootPassword: <path:kv/data/k3s/argocd/mailu#mysql_root_password>

      database: mailu
      user: mailu
      password: <path:kv/data/k3s/argocd/mailu#mysql_password>

      roundcubeDatabase: roundcube
      roundcubeUser: roundcube
      roundcubePassword: <path:kv/data/k3s/argocd/mailu#roundcube_password>

  certmanager:
    issuerName: letsencrypt-prod

  ingress:
    tlsFlavor: cert
    annotations:
      kubernetes.io/ingress.class: "nginx"

  front:
    hostPort:
      enabled: false

    externalService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 31.172.117.49

  persistence:
    single_pvc: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClass: "csi-cinder-sc-delete-all-zones"

  postfix:
    image:
      repository: sh4ke/mailu-postfix
      tag: latest

  rspamd:
    resources:
      limits:
        memory: 500Mi

  webdav:
    enabled: true
