mailu:
  hostnames:
    - mail.ws.sh4ke.rocks

  domain: ws.sh4ke.rocks
  subnet: 10.44.0.0/16

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - k3s-server-1

  secretKey: <path:kv/data/k3s/argocd/mailu#secret_key>

  initialAccount:
    enabled: true
    username: admin
    domain: ws.sh4ke.rocks
    password: <path:kv/data/k3s/argocd/mailu#initial_admin_password>

  persistence:
    single_pvc: false

  global:
    database:
      roundcube:
        password: <path:kv/data/k3s/argocd/mailu#postgresUserPassword>

  postgresql:
    enabled: true
    auth:
      postgresPassword: <path:kv/data/k3s/argocd/mailu#postgresPassword>
      password: <path:kv/data/k3s/argocd/mailu#postgresUserPassword>
    primary:
      persistance:
        enabled: true
        storageClass: longhorn
        size: 1Gi

  ingress:
    tlsFlavorOverride: mail
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  front:
    hostPort:
      enabled: false
    externalService:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 31.172.117.18
    updateStrategy:
      type: Recreate

  oleTools:
    updateStrategy:
      type: Recreate

  admin:
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate

  redis:
    master:
      persistence:
        size: 1Gi
        storageClass: longhorn

  postfix:
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate

  dovecot:
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate

  rspamd:
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate

  clamav:
    persistence:
      size: 1Gi
      storageClass: longhorn

  webmail:
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate

  webdav:
    enabled: true
    persistence:
      size: 1Gi
      storageClass: longhorn
    updateStrategy:
      type: Recreate
