renovate:
  apiVersionOverrides:
    cronjob: 'batch/v1'
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.os.sh4ke.rocks/api/v1",
        "token": "<path:kv/data/k3s/argocd/revovate#gitea_token>",
        "autodiscover": "true",
        "printConfig": true,
        "redisUrl": "redis"
      }
  redis:
    enabled: true
