renovate:
  apiVersionOverrides:
    cronjob: 'batch/v1'
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://gitea.os.sh4ke.rocks/api/v1",
        "token": "<path:kv/data/k3s/argocd/renovate#gitea_token>",
        "autodiscover": "true",
        "printConfig": true,
        "redisUrl": "redis"
      }
  redis:
    enabled: true
    global:
      storageClass: csi-cinder-sc-delete-all-zones

  secrets:
    GITHUB_COM_TOKEN: "<path:kv/data/k3s/argocd/renovate#github_token>"
