apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
spec:
  template:
    spec:
      containers:
        - name: owncloud
          image: docker.io/bitnami/owncloud:10.8.0-debian-10-r97
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          env:
            - name: OWNCLOUD_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-mariadb-from-seal
                  key: mariadb-password
            - name: OWNCLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-from-seal
                  key: owncloud-password
            - name: OWNCLOUD_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-from-seal
                  key: smtp-password
