apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owncloud-mariadb
spec:
  template:
    spec:
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: owncloud-mariadb-from-seal
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: owncloud-mariadb-from-seal
        name: mariadb
