apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owncloud-mariadb
spec:
  template:
    spec:
      containers:
        - name: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-mariadb-from-seal
                  key: mariadb-root-password
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-mariadb-from-seal
                  key: mariadb-password
