docker-mailserver:
  demoMode:
    # demoMode.enabled ignores the contents of helm-chart/docker-mailserver/config and creates minimal static configuration to be used instead. A single account (user "user@example.com", password "password") will be configured for the purpose of validating core functions and connectivity, before applying user config
    enabled: false

  ssl:
    issuer:
      name: letsencrypt-prod
    dnsname: mail.sh4ke.rocks

  domains:
    - mail.sh4ke.rocks

  pod:
    override_hostname: "mail.sh4ke.rocks"
    enable_fail2ban: 1

    ssl_type: letsencrypt

  service:
    loadBalancer:
      allowedIps:
        - "213.95.155.192/24"

      hostName: "mail.sh4ke.rocks"

  persistence:
    size: "5Gi"
    storageClass: csi-cinder-sc-delete-all-zones

  rainloop:
    enabled: true
    persistence:
      storageClass: csi-cinder-sc-delete-all-zones

    ingress:
      hosts:
        - rainloop.k3s.sh4ke.rocks

      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx
      tls:
        - secretName: rainloop-k3s-sh4ke-rocks
          hosts:
            - rainloop.k3s.sh4ke.rocks
