apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'shake@git.sh4ke.rocks:sh4ke/k8s-projects.git'
    path: pacman
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-kustomize
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pacman
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
