pacman:
  service:
    type: ClusterIP

  ingress:
    create: true
    class: nginx
    host: "pacman.k3s.sh4ke.rocks"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls:
      enabled: true
      secretName: pacman-k3s-sh4ke-rocks-tls
