---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-pgsql-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/k3s/argocd/gitea"
data:
  postgres-password: <giteaPostgresPassword|base64encode>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/k3s/argocd/gitea"
data:
  username: {{ "admin" | b64enc }}
  password: <giteaAdminPassword|base64encode>
