---
kind: pipeline
type: docker
name: setup wavestack

steps:
  - name: gitea automation
    image: sh4ke/docker-devoops-tools
    pull: always
    commands:
      - |
        cd gitea/repos
        id=$(curl -X "GET" "https://gitea.sh4ke.rocks/api/v1/user?access_token=a370e8b5657b3860d502d813cd7e2e478b320fb5" -H "accept: application/json" | jq '.id')
        echo $id
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TF_AUTOMATION_TOKEN

