---
kind: pipeline
type: docker
name: setup wavestack

steps:
  - name: gitea automation
    image: sh4ke/docker-devoops-tools
    pull: always
    commands:
      - cd gitea/repos
      - bash gitea_automation.sh $GITEA_TOKEN
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TF_AUTOMATION_TOKEN

