---
kind: pipeline
type: docker
name: setup wavestack

steps:
  - name: install k3s basic cluster
    image: hashicorp/terraform:1.4.4
    commands:
      - cd gitea/repos
      - terraform init
      - terraform apply
    environment:
      TF_IN_AUTOMATION: true
      TF_INPUT: 0
      TF_CLI_ARGS_apply: "-auto-approve"
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      TF_VAR_gitea_token:
        from_secret: GITEA_TF_AUTOMATION_TOKEN

# host_aliases:
#   - ip: 192.168.178.55
#     hostnames:
#       - ganymed
