# creation rules are evaluated sequentially, the first match wins
creation_rules:
      # upon creation of a file that matches the pattern *secret.yaml,
      - path_regex: secrets\.yaml$
        pgp: 'F89BB35B5CAE2132B2E85764D10F7AD6DA20EEF7'
        # hc_vault_uris: "http://localhost:8200/v1/sops/keys/thirdkey"
