---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-sh4ke-rocks
spec:
  secretName: alertmanager-sh4ke-rocks-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: alertmanager.sh4ke.rocks
  dnsNames:
  - alertmanager.sh4ke.rocks
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-sh4ke-rocks
spec:
  secretName: grafana-sh4ke-rocks-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.sh4ke.rocks
  dnsNames:
  - grafana.sh4ke.rocks
...

