kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder-sc-delete-all-zones
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      alertmanagerConfigNamespaceSelector:
        matchLabels:
          alertmanagerconfig: enabled

  grafana:
    adminPassword: <path:kv/data/k3s/argocd/kube-prometheus#grafanaAdminPassword>
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"

  prometheus:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    prometheusSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: csi-cinder-sc-delete-all-zones
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      serviceMonitorNamespaceSelector:
        matchLabels:
          alertmanagerconfig: enabled
      podMonitorNamespaceSelector:
        matchLabels:
          alertmanagerconfig: enabled
