kube-prometheus-stack:
  alertmanager:
    ingress:
      hosts:
        - alertmanager.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: alertmanager-os-sh4ke-rocks-tls
          hosts:
          - alertmanager.os.sh4ke.rocks

    config:
      receivers:
        - name: 'null'
        - name: telegram
          telegram_configs:
            - bot_token: <path:kv/data/k3s/argocd/kube-prometheus#telegramApiToken>
              api_url: "https://api.telegram.org"
              chat_id: 247311808
              parse_mode: "HTML"

  grafana:
    ingress:
      hosts:
        - grafana.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: grafana-os-sh4ke-rocks-tls
          hosts:
          - grafana.os.sh4ke.rocks

  prometheus:
    ingress:
      hosts:
        - prometheus.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: prometheus-os-sh4ke-rocks-tls
          hosts:
          - prometheus.os.sh4ke.rocks
