kube-prometheus-stack:
  alertmanager:
    ingress:
      hosts:
        - alertmanager.ws.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: alertmanager-ws-sh4ke-rocks-tls
          hosts:
          - alertmanager.ws.sh4ke.rocks

    config:
      receivers:
        - name: 'null'
        - name: telegram
          telegram_configs:
            - bot_token: <path:kv/data/k3s/argocd/kube-prometheus#telegramApiToken>
              api_url: "https://api.telegram.org"
              chat_id: 833373832
              parse_mode: "HTML"

  grafana:
    ingress:
      hosts:
        - grafana.ws.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: grafana-ws-sh4ke-rocks-tls
          hosts:
          - grafana.ws.sh4ke.rocks

  prometheus:
    ingress:
      hosts:
        - prometheus.ws.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: prometheus-ws-sh4ke-rocks-tls
          hosts:
          - prometheus.ws.sh4ke.rocks

  prometheusOperator:
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
