kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - alertmanager.sh4ke.rocks
      paths:
        - /
      tls:
        - hosts:
            - alertmanager.sh4ke.rocks
          secretName: alertmanager-sh4ke-rocks-tls
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
  grafana:
    defaultDashboardsTimezone: "Europe/Berlin"
    adminPassword: "k3*RJW2hmaHRJHNk"
    grafana.ini:
      server:
        root_url: https://grafana.sh4ke.rocks
      smtp:
        enabled: true
        existingSecret: ""
        host: "in-v3.mailjet.com:587"
        user: "72f7fc0111ac7842d08c8e1e464324dd"
        password: "e9f800478ba1b1069511e0f8485e6fe8"
        from_address: "noreply@sh4ke.rocks"
    persistence:
      type: pvc
      enabled: true
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 50Gi
      finalizers:
        - kubernetes.io/pvc-protection
    ingress:
      enabled: true
      ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.sh4ke.rocks
    tls:
      - hosts:
          - grafana.sh4ke.rocks
        secretName: grafana-sh4ke-rocks-tls
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - prometheus.sh4ke.rocks
      paths:
        - /
      pathType: ImplementationSpecific
      tls:
        - secretName: prometheus-sh4ke-rocks-tls
          hosts:
            - prometheus.sh4ke.rocks
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi
