kube-prometheus-stack:
  alertmanager:
    ingress:
      hosts:
        - alertmanager.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: alertmanager-os-sh4ke-rocks-tls
          hosts:
          - alertmanager.os.sh4ke.rocks 

  grafana:
    ingress:
      hosts:
        - grafana.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: grafana-os-sh4ke-rocks-tls
          hosts:
          - grafana.os.sh4ke.rocks 

  prometheus:
    ingress:
      hosts:
        - prometheus.os.sh4ke.rocks
      paths:
        - /
      tls:
        - secretName: prometheus-os-sh4ke-rocks-tls
          hosts:
          - prometheus.os.sh4ke.rocks 
