rook-ceph-cluster:
  ingress:
    dashboard: {}
      annotations:
        # kubernetes.io/ingress.class: nginx
        # external-dns.alpha.kubernetes.io/hostname: example.com
        # nginx.ingress.kubernetes.io/rewrite-target: /ceph-dashboard/$2
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      # If the dashboard has ssl: true the following will make sure the NGINX Ingress controller can expose the dashboard correctly
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/server-snippet: |
          proxy_ssl_verify off;
      host:
        name: ceph.k3s.sh4ke.rocks
        path: "/ceph-dashboard(/|$)(.*)"
      tls:
        - hosts:
            - ceph.k3s.sh4ke.rocks
          secretName: ceph-k3s-sh4ke-rocks-tls
      ingressClassName: nginx
