apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: drone
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: PLUGIN_PARAMS
          value: "-f values.yaml -f values.openstack.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: drone
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
