resources:
  - all.yaml
patches:
  - path: kustomizations/controllerplugin-rbac.yaml
    target:
      kind: ClusterRole
      name: csi-attacher-role
  - path: kustomizations/nodeplugin-rbac.yaml
    target:
      kind: ClusterRole
      name: csi-nodeplugin-role
patchesJson6902:
  - path: kustomizations/controllerplugin-deployment.yaml
    target:
      kind: Deployment
      version: apps/v1
      name: openstack-cinder-csi-controllerplugin

