openstack-cinder-csi:
  secret:
    enabled: true
    create: true
    name: cinder-csi-cloud-config
  storageClass:
    enabled: true
    delete:
      isDefault: false
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true
