openstack-cinder-csi:
  # Log verbosity level.
  # See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
  # for description of individual verbosity levels.
  logVerbosityLevel: 4

  secret:
    enabled: true
    create: true
    name: cinder-csi-cloud-config
    data:
      cloud-config: |-
        [Global]
        auth-url="https://de-nbg6-1.noris.cloud:5000/v3"
        username="mwittig"
        user-domain-name="noris.de"
        password="***REMOVED***"
        tenant-id=8e3e72a2e75c44eba74be23856b02fa2
        tenant-name=mwittig
        tenant-domain-id=0fd4315f3f784ee2a37cfd9657385fe5
        region=de-nbg6-1
        tls-insecure=true

  storageClass:
    enabled: true
    delete:
      isDefault: false
      allowVolumeExpansion: true
    retain:
      isDefault: false
      allowVolumeExpansion: true

