{{- range $k,$v:= .Values.apps }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $k }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $v.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ $k }}
            port:
              number: {{ $v.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $v.hostname }}
    secretName: {{ $v.hostname | replace "." "-" }}-tls
{{- end }}

