vaultwarden:
  common:
      global:
        annotations:
          avp.kubernetes.io/path: "kv/data/k3s/argocd/vaultwarden"
  env:
    SIGNUPS_VERIFY: true
    ADMIN_TOKEN: <admin-token>
    SMTP_HOST: <smtp-host>
    SMTP_FROM: noreply@sh4ke.rocks
    SMTP_FROM_NAME: Vaultwarden
    SMTP_SECURITY: starttls # ("starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
    SMTP_PORT: 587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 is outdated and used with Implicit TLS.
    SMTP_USERNAME: <smtp-username>
    SMTP_PASSWORD: <smtp-password>
    DATABASE_URL: mysql://<username>:<password>@vaultwarden-mariadb:3306/<database>
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: vaultwarden.k3s.sh4ke.rocks
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                port: 80
            - path: /notifications/hub
              pathType: Prefix
              service:
                port: 3012
      tls:
        - secretName: vaultwarden-k3s-sh4ke-rocks-tls
          hosts:
            - vaultwarden.k3s.sh4ke.rocks
  persistence:
    config:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
  mariadb:
    enabled: true
    commonAnnotations:
      avp.kubernetes.io/path: "kv/data/k3s/argocd/vaultwarden"
    auth:
      username: "<username>"
      password: "<password>"
      rootPassword: "<rootPassword>"
      database: "<database>"
    primary:
      persistence:
        storageClass: csi-cinder-sc-delete-all-zones
