vaultwarden:
  common:
      global:
        annotations:
          avp.kubernetes.io/path: "kv/data/k3s/argocd/vaultwarden"
  env:
    SIGNUPS_VERIFY: true
    ADMIN_TOKEN: <admin-token>
    # SMTP_HOST: <smtp-host>
    # SMTP_FROM: noreply@sh4ke.rocks
    # SMTP_FROM_NAME: Vaultwarden
    # SMTP_SECURITY: starttls # ("starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
    # SMTP_PORT: 587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 is outdated and used with Implicit TLS.
    # SMTP_USERNAME: <smtp-username>
    # SMTP_PASSWORD: <smtp-password>
    DATABASE_URL: mysql://<username>:<password>@vaultwarden-mariadb:3306/<database>
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
  persistence:
    config:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
  mariadb:
    enabled: true
    commonAnnotations:
      avp.kubernetes.io/path: "kv/data/k3s/argocd/vaultwarden"
    auth:
      username: "<username>"
      password: "<password>"
      rootPassword: "<rootPassword>"
      database: "<database>"
    primary:
      persistence:
        storageClass: csi-cinder-sc-delete-all-zones
        storageClassBackup: nfs-csi

backup:
  schedule: "10 4 * * *"
  image: docker.io/bitnami/mariadb:10.6.8-debian-11-r9
  shellCommand: mysqldump -u ${MARIADB_USER} -p${MARIADB_PASSWORD} ${MARIADB_DATABASE} > /backup/vaultwarden_dump.$(date +"%d-%m-%Y").sql
  env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: vaultwarden-mariadb
    - name: MARIADB_USER
      value: tjllrhhdxmpgxxee
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: vaultwarden-mariadb
  volumeMounts:
    - mountPath: /bitnami/mariadb
      name: data
    - mountPath: /backup
      name: mariadb-backup
    - mountPath: /opt/bitnami/mariadb/conf/my.cnf
      name: config
      subPath: my.cnf
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: data-vaultwarden-mariadb-0
    - name: mariadb-backup
      persistentVolumeClaim:
        claimName: mariadb-backup
    - configMap:
        defaultMode: 420
        name: vaultwarden-mariadb
      name: config
  matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
        - mariadb
  permissions:
    dirs: /backup
    owner: "1001"
    group: "1001"
