---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin-avp-helm
data:
  plugin.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - "sh"
            - "-c"
            - "ls Chart.yaml && find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE . --include-crds | argocd-vault-plugin generate -"]
      lockRepo: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin-avp-helm-kustomize
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - "sh"
            - "-c"
            - "ls kustomization.yaml && find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      init:
        command: ["sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm | argocd-vault-plugin generate -"]
      lockRepo: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-build-with-helm
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-build-with-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - "sh"
            - "-c"
            - "ls kustomization.yaml"
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm"]
      lockRepo: false
