apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ssh://git@gitea.ws.sh4ke.rocks:2222/sh4ke/k8s-projects.git'
    path: gitea
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: PLUGIN_PARAMS
          value: "-f values.yaml -f values.openstack.yaml"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
