---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-sh4ke-rocks
spec:
  secretName: gitea-sh4ke-rocks-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gitea.sh4ke.rocks
  dnsNames:
  - gitea.sh4ke.rocks
...
