gitea:
  service:
    ssh:
      loadBalancerIP: 31.172.116.135

  ingress:
    hosts:
      - host: gitea.ws.sh4ke.rocks
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-ws-sh4ke-rocks-tls
        hosts:
          - gitea.ws.sh4ke.rocks

backup:
  volumes:
    - name: gitea-data
      persistentVolumeClaim:
        claimName: data-gitea-0
    - name: data-gitea-0-backup
      persistentVolumeClaim:
        claimName: data-gitea-0
