gitea:
  image:
    rootless: true

  service:
    ssh:
      type: LoadBalancer
      port: 2222

  ingress:
    enabled: true
    className: nginx
    apiVersion: networking.k8s.io/v1
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"

  persistence:
    storageClass: csi-cinder-sc-delete-all-zones

  commonAnnotations:
    avp.kubernetes.io/path: "kv/data/k3s/argocd/gitea"

  statefulset:
    annotations:
      avp.kubernetes.io/path: "kv/data/k3s/argocd/gitea"

  gitea:
    admin:
      username: gitea_admin
      password: <giteaAdminPassword>
      email: "michael.wittig@posteo.de"

    config:
      APP_NAME: "Gitea: This Is Why We Don't Push To Production On Fridays"
      RUN_MODE: prod
      server:
        SSH_PORT: 2222
      picture:
        DISABLE_GRAVATAR: true
      security:
        PASSWORD_COMPLEXITY: spec
        MIN_PASSWORD_LENGTH: 8
      service:
        DISABLE_REGISTRATION: true
        DEFAULT_KEEP_EMAIL_PRIVATE: true
        DEFAULT_ORG_VISIBILITY: private
        DEFAULT_USER_IS_RESTRICTED: true
        REQUIRE_SIGNIN_VIEW: true

  postgresql:
    global:
      postgresql:
        postgresqlPassword: <giteaPostgresPassword>

    persistence:
      size: 1Gi
      storageClass: csi-cinder-sc-delete-all-zones
