---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud
subsets:
- addresses:
  - ip: {{ .Values.nextcloud.ip }}
  ports:
  - name: nextcloud 
    port: {{ .Values.nextcloud.port }}
    protocol: TCP
