---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
  - name: nextcloud
    port: 80
    protocol: TCP
    targetPort: {{ .Values.nextcloud.port }}
  clusterIP: None
  type: ClusterIP
