paperless:
  env:
    PAPERLESS_URL: https://paperless.ws.sh4ke.rocks

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: paperless.ws.sh4ke.rocks
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-k3s-sh4ke-rocks-tls
          hosts:
            - paperless.ws.sh4ke.rocks

  persistence:
    data:
      enabled: true
      storageClass: nfs-csi
      size: 1Gi
    media:
      enabled: true
      storageClass: nfs-csi
      size: 8Gi
    consume:
      enabled: true
      storageClass: nfs-csi
      size: 1Gi
    export:
      enabled: true
      storageClass: nfs-csi
      size: 1Gi

  postgresql:
    primary:
      persistence:
        storageClass: nfs-csi
