#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
paperless:
  common:
    controller:
      annotations:
        avp.kubernetes.io/path: "kv/data/k3s/argocd/paperless"

  # -- See the following files for additional environment variables:
  # https://github.com/jonaswinkler/paperless-ng/tree/master/docker/compose/
  # https://github.com/jonaswinkler/paperless-ng/blob/master/paperless.conf.example
  # @default -- See below
  env:
    # -- Project name
    COMPOSE_PROJECT_NAME: paperless
    # -- Redis to use
    PAPERLESS_REDIS: redis://paperless-ng-redis-master:6379
    # -- OCR languages to install
    PAPERLESS_OCR_LANGUAGE: deu
    PAPERLESS_OCR_LANGUAGES: "deu eng"
    # USERMAP_UID: 1000
    # USERMAP_GID: 1000
    PAPERLESS_TIME_ZONE: Europe/Berlin
    # -- Database
    PAPERLESS_DBHOST: paperless-ng-postgresql
    PAPERLESS_DBNAME: <dbname>
    PAPERLESS_DBUSER: <dbusername>
    PAPERLESS_DBPASS: <dbpassword>
    # Tika + Gotenberg
    PAPERLESS_TIKA_ENABLED: 1
    PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-ng-gotenberg:3000
    PAPERLESS_TIKA_ENDPOINT: http://paperless-ng-tika:9998

    # Handling inotify not working on NFS
    # PAPERLESS_CONSUMER_POLLING: 30
    PAPERLESS_CONSUMER_RECURSIVE: 1

    PAPERLESS_ENABLE_UPDATE_CHECK: true
    PAPERLESS_SECRET_KEY: <secretKey>
    PAPERLESS_URL: https://paperless.k3s.sh4ke.rocks

    PAPERLESS_ADMIN_USER: <paperlessAdminUser>
    PAPERLESS_ADMIN_PASSWORD: <paperlessAdminPassword>
    PAPERLESS_ADMIN_MAIL: <paperlessAdminMail>

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: paperless.k3s.sh4ke.rocks
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: paperless-k3s-sh4ke-rocks-tls
          hosts:
            - paperless.k3s.sh4ke.rocks

  persistence:
    data:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
      size: 1Gi
    media:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
      size: 1Gi
    consume:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
      size: 1Gi
    export:
      enabled: true
      storageClass: csi-cinder-sc-delete-all-zones
      size: 1Gi

  redis:
    enabled: true
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0
      persistence:
        enabled: false

  postgresql:
    enabled: true
    commonAnnotations:
      avp.kubernetes.io/path: "kv/data/k3s/argocd/paperless"

    auth:
      postgresPassword: "<postgresPassword>"
      username: "<dbusername>"
      password: "<dbpassword>"
      database: "<dbname>"
      replicationPassword: "<replicationPassword>"

    primary:
      persistence:
        enabled: true
        storageClass: csi-cinder-sc-delete-all-zones
        accessModes:
          - ReadWriteOnce
