apiVersion: v1
kind: Service
metadata:
  name: mosquitto-node-svc
  namespace: mosquitto
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: mosquitto
    app.kubernetes.io/name: mosquitto
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 1883
      targetPort: 1883
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31883
