mosquitto:
  service:
    main:
      ports:
        http:
          enabled: true
          port: 8080
  persistence:
    data:
      enabled: true
      storageClass: "nfs-client"
      accessMode: "ReadWriteOnce"
      size: 10Gi
