mosquitto:
  service:
    main:
      ports:
        mqtt:
          enabled: true
          nodePort: 1883
          svcType: NodePort
  persistence:
    data:
      enabled: true
      storageClass: "nfs-client"
      accessMode: "ReadWriteOnce"
      size: 10Gi
