kubeinvaders:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostName: "kubeinvaders.k3s.sh4ke.rocks"
    tls:
      - hosts:
          - kubeinvaders.k3s.sh4ke.rocks
    secretName: kubeinvaders-k3s-sh4ke-rocks-tls
