nextcloud:
  ingress:
    tls:
      - secretName: nextcloud-ws-sh4ke-rocks-tls
        hosts:
          - nextcloud.ws.sh4ke.rocks
  nextcloud:
    host: nextcloud.ws.sh4ke.rocks

  mariadb:
    primary:
      persistence:
        storageClass: csi-cinder-sc-delete-all-zones

  redis:
    enabled: false
    global:
      storageClass: nfs-csi

  persistence:
    storageClass: nfs-csi

    nextcloudData:
      storageClass: nfs-csi
