home-assistant:
  env:
    TZ: "Europe/Berlin"

  persistence:
    config:
      enabled: true
      storageClass: "nfs-client"

  securityContext:
    # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
    privileged:  false

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true

  # -- Enable devices to be discoverable
  hostNetwork: true

  # -- When hostNetwork is true set dnsPolicy to ClusterFirstWithHostNet
  dnsPolicy: ClusterFirstWithHostNet

  mariadb:
    enabled: true
    primary:
      persistence:
        enabled: true
        storageClass: "nfs-client"
