chartmuseum:
  env:
    open:
      AUTH_ANONYMOUS_GET: true
      DISABLE_API: false
    secret:
      BASIC_AUTH_USER: "Sh4kE"
      BASIC_AUTH_PASS: <path:kv/data/k3s/argocd/chartmuseum#password>

  persistence:
    enabled: true
    storageClass: "csi-cinder-sc-delete-all-zones"
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingressClassName: nginx
    hosts:
     - name: chartmuseum.os.sh4ke.rocks
       path: /
       ## Set this to true in order to enable TLS on the ingress record
       tls: true
       ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
       ## Secrets must be added manually to the namespace
       tlsSecret: chartmuseum.os.sh4ke.rocks-tls
