apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: infra-apps
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: cilium/qa
    targetRevision: HEAD
    plugin:
      name: kustomize-build-with-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
