apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: cilium
spec:
  project: default
  source:
    kustomize:
      version: default
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: cilium/qa
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cilium
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
