apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: cilium/qa
    targetRevision: HEAD
    plugin:
      name: kustomize-build-with-helm
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumIdentity

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cilium
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
