apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam
  namespace: argocd
spec:
  project: infra-apps
  source:
    repoURL: 'git@github.com/Sh4kE/k8s-projects.git'
    path: iam
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

