apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: infra-apps
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: kube-prometheus/qa
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm-kustomize
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-prometheus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
