apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portworx-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Sh4kE/k8s-projects.git
    targetRevision: main
    path: portworx-operator/qa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portworx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
