kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_TYPE: dmF1bHQK                                                   # vault
  AVP_AUTH_TYPE: azhzCg==                                              # k8s
  AVP_K8S_ROLE: YXJnb2NkCg==                                           # argocd
  VAULT_ADDR: aHR0cDovL3ZhdWx0LnZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgyMDAK # http://vault.vault.svc.cluster.local:8200
