kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_AUTH_TYPE: YXBwcm9sZQo=
  AVP_ROLE_ID: YXJnb2NkCg==
  AVP_SECRET_ID: NDA4YWUxOWQtZTdmYy05ODgzLTNjZDMtMmJiY2ZkNjcwYWNkCg==
  AVP_TYPE: dmF1bHQK
  VAULT_ADDR: aHR0cDovL3ZhdWx0LnZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgyMDAK
