kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: argocd
  AVP_SECRET_ID: 408ae19d-e7fc-9883-3cd3-2bbcfd670acd
  AVP_TYPE: vault
  VAULT_ADDR: 'http://vault.vault.svc.cluster.local:8200'
