kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  ARGOCD_ENV_AVP_TYPE: dmF1bHQ=                                                   # vault
  ARGOCD_ENV_AVP_AUTH_TYPE: azhz                                                  # k8s
  ARGOCD_ENV_AVP_K8S_ROLE: YXJnb2Nk                                               # argocd
  ARGOCD_ENV_VAULT_ADDR: aHR0cDovL3ZhdWx0LnZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgyMDA= # http://vault.vault.svc.cluster.local:8200
