kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: ba3ad8c0-f698-1528-db96-3d6910eadba0
  AVP_SECRET_ID: 03bbc24f-cf97-1bc2-bdd3-b3f2d20e4b59
  AVP_TYPE: vault
  VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
