apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'shake@git.sh4ke.rocks:sh4ke/k8s-projects.git'
    path: nfs-subdir-external-provisioner
    targetRevision: HEAD
    values: 'values.yaml'
#    plugin:
#      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-subdir-external-provisioner
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
