---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: cilium

helmCharts:
  - name: cilium
    includeCRDs: true
    releaseName: cilium
    version: 1.13.2
    repo: https://helm.cilium.io/
    valuesFile: values.yaml
    namespace: cilium

resources:
  - resources/ns.yaml
  - resources/network_policy.yaml

namespace: cilium
