---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: argocd

resources:
  - https://install.portworx.com/2.13?operator=true&mc=false&kbver=1.25.7&ns=portworx&oem=esse&user=fbb16180-974b-4b8c-9169-43a3e6e72086&b=true&c=wavestack-9a7f8867-2e23-454d-ac3f-6abfbfafd998&stork=false&csi=true&mon=false&tel=false&st=k8s&promop=false
