ingress-nginx:
  controller:
    ingressClassResource:
      default: true
    metrics:
      enabled: false
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
      serviceMonitor:
        enabled: false 
