apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: chartmuseum
  namespace: chartmuseum
  releaseName: chartmuseum
  repo: https://chartmuseum.github.io/charts
  valuesFile: values.yaml
  version: 3.9.3

patches:
- path: kustomizations/deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: chartmuseum
