harbor:
  adminPassword: <path:kv/data/k3s/argocd/harbor#admin_password>
  logLevel: warn
  exposureType: ingress

  service:
    type: ClusterIP

  ingress:
    core:
      ingressClassName: "nginx"
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    notary:
      ingressClassName: "nginx"
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

  persistence:
    resourcePolicy: 'delete'
    persistentVolumeClaim:
      registry:
        storageClass: csi-cinder-sc-delete-all-zones
      jobservice:
        storageClass: csi-cinder-sc-delete-all-zones
      chartmuseum:
        storageClass: csi-cinder-sc-delete-all-zones
      trivy:
        storageClass: csi-cinder-sc-delete-all-zones

  postgresql:
    auth:
      postgresPassword: <path:kv/data/k3s/argocd/harbor#postgres_password>
