apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'shake@git.sh4ke.rocks:sh4ke/k8s-projects.git'
    path: snapshot-controller
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: snapshot-controller
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
