apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ssh://git@gitea.os.sh4ke.rocks:2222/sh4ke/k8s-projects.git'
    path: vault
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values.wavestack.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: "*"
      kind: "MutatingWebhookConfiguration"
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
