vault:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: vault.k3s.sh4ke.rocks
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: vault-k3s-sh4ke-rocks
          hosts:
            - vault.k3s.sh4ke.rocks
    dataStorage:
      storageClass: csi-cinder-sc-delete-all-zones
      auditStorage:
        enabled: true
        storageClass: csi-cinder-sc-delete-all-zones
    ha:
      enabled: true
      raft:
        enabled: false
  ui:
    enabled: false
