vault:
  server:
    dataStorage:
      storageClass: csi-cinder-sc-delete-all-zones
    auditStorage:
      storageClass: csi-cinder-sc-delete-all-zones
    ingress:
      hosts:
        - host: vault.os.sh4ke.rocks
          paths: []
      tls:
        - secretName: vault-os-sh4ke-rocks
          hosts:
            - vault.os.sh4ke.rocks
