vault:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    dataStorage:
      storageClass: longhorn
      size: 2Gi
    auditStorage:
      enabled: true
      size: 2Gi
      storageClass: longhorn
    ha:
      enabled: true
      raft:
        enabled: true
