vault:
  server:
    ingress:
      hosts:
        - host: vault.os.sh4ke.rocks
          paths: []
      tls:
        - secretName: vault-os-sh4ke-rocks
          hosts:
            - vault.os.sh4ke.rocks
