---
apiVersion: v1
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-build-with-helm
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - "sh"
            - "-c"
            - "ls kustomization.yaml"
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm"]
      lockRepo: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: kustomize-build-with-helm
