---
apiVersion: v1
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm-kustomize
    spec:
      allowConcurrency: true
      discover:
        find:
          command:
            - "sh"
            - "-c"
            - "ls kustomization.yaml && find . -name '*.yaml' | xargs -I {} grep \"<path\\|avp\\.kubernetes\\.io\" {} | grep ."
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-helm | argocd-vault-plugin generate -"]
      lockRepo: false
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
  name: cmp-plugin-avp-helm-kustomize
