---
apiVersion: v1
data:
  kustomize.buildOptions: --enable-helm
  kustomize.path.default: /usr/local/bin/kustomize
  sshConfigs: |
    Host gitea.sh4ke.rocks
        KexAlgorithms ecdh-sha2-nistp521
        PubkeyAcceptedAlgorithms +ssh-rsa
    Host gitea.os.sh4ke.rocks
        KexAlgorithms ecdh-sha2-nistp521
        PubkeyAcceptedAlgorithms +ssh-rsa
    Host gitea.ws.sh4ke.rocks
        KexAlgorithms ecdh-sha2-nistp521
        PubkeyAcceptedAlgorithms +ssh-rsa
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
