---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
spec:
  rules:
  - host: {{ .Values.paperless.domain }}
    http:
      paths:
      - backend:
          service:
            name: paperless 
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.paperless.domain }}
    secretName: {{ .Values.paperless.domain | replace "." "-" }}-tls
