apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: apply-pss-restricted-profile
spec:
  rules:
  - name: add-pss-fields
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - privatebin
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
          containers:
          - (name): "?*"
            securityContext:
              privileged: false
              capabilities:
                drop:
                - ALL
              allowPrivilegeEscalation: false
