---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: clusterpolicies.kyverno.io

---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: policies.kyverno.io
