apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: chartmuseum/qa
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chartmuseum
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
