apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeclarity
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: kubeclarity/qa
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeclarity
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
