apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: paperless-wireguard
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values.wavestack.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: paperless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
