apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/name: mariadb
  name: mariadb-backup
spec:
  accessModes: {{ .Values.mariadb.primary.persistence.accessModes }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.mariadb.primary.persistence.storageClassBackup }}
  resources:
    requests:
      storage: {{ .Values.mariadb.primary.persistence.size }}
