---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - name: argocd-repo-server
          volumeMounts:
            - name: ssh-configs
              mountPath: /home/argocd/.ssh/
          envFrom:
            - secretRef:
                name: argocd-vault-plugin-credentials
        - name: avp-helm
          command: [/var/run/argocd/argocd-cmp-server]
          image: sh4ke/argocd-plugins
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          envFrom:
            - secretRef:
                name: argocd-vault-plugin-credentials
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
            - mountPath: /home/argocd/cmp-server/config/
              name: cmp-plugin-avp-helm
            - mountPath: /tmp
              name: cmp-plugin-avp-helm-tmp
        - name: avp-helm-kustomize
          command: [/var/run/argocd/argocd-cmp-server]
          image: sh4ke/argocd-plugins
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          envFrom:
            - secretRef:
                name: argocd-vault-plugin-credentials
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
            - mountPath: /home/argocd/cmp-server/config/
              name: cmp-plugin-avp-helm-kustomize
            - mountPath: /tmp
              name: cmp-plugin-avp-helm-kustomize-tmp
        - name: kustomize-build-with-helm
          command: [/var/run/argocd/argocd-cmp-server]
          image: sh4ke/argocd-plugins
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          envFrom:
            - secretRef:
                name: argocd-vault-plugin-credentials
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
            - mountPath: /home/argocd/cmp-server/config/
              name: kustomize-build-with-helm
            - mountPath: /tmp
              name: kustomize-build-with-helm-tmp
      volumes:
        - name: cmp-plugin-avp-helm
          configMap:
            name: cmp-plugin-avp-helm
        - name: cmp-plugin-avp-helm-kustomize
          configMap:
            name: cmp-plugin-avp-helm-kustomize
        - name: kustomize-build-with-helm
          configMap:
            name: kustomize-build-with-helm
        - name: cmp-plugin-avp-helm-tmp
          emptyDir: {}
        - name: cmp-plugin-avp-helm-kustomize-tmp
          emptyDir: {}
        - name: kustomize-build-with-helm-tmp
          emptyDir: {}
        - name: ssh-configs
          configMap:
            name: argocd-cm
            items:
              - key: sshConfigs
                path: config
