freshrss:
  image:
    tag: 1.21.0
  persistence:
    enabled: true
    storageClassName: "longhorn"
    size: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - freshrss.ws.sh4ke.rocks
    tls:
      - hosts:
        - freshrss.ws.sh4ke.rocks
        secretName: freshrss-ws-sh4ke-rocks-tls
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          password: <path:kv/data/k3s/argocd/gitea#giteaPostgresPassword>
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 1Gi
