netdata:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - netdata.k3s.sh4ke.rocks
    tls:
      - secretName: netdata-k3s-sh4ke-rocks-tls
        hosts:
          - netdata.k3s.sh4ke.rocks
  parent:
    database:
      storageclass: "ceph-block"
    alarms:
      storageclass: "ceph-block"
    configs:
      netdata:
        data: |
          [global]
            memory mode = dbengine

          [plugins]
            cgroups = yes
            tc = yes
            enable running new plugins = yes
            check for new plugins every = 72000
            python.d = yes
            charts.d = yes
            go.d = yes
            node.d = yes
            apps = yes
            proc = yes
            idlejitter = yes
            diskspace = yes
    claiming:
      enabled: true
      token: BBHNO9oI6dJQvBD90fxx7FtUc1SvDfAptvmQmFoMwmDkiOi7cZOQTplccAjaue7gWQYDgCHXS25A3BIyPFadZU-laA6BCZtJ9JhZNnzPnGOaWWqeCwa2Vn4_3HnWtJMSZqK_vis
      rooms: 0b7b71f1-2140-433f-99d7-534d000f81c9
  child:
    claiming:
      enabled: true
      token: BBHNO9oI6dJQvBD90fxx7FtUc1SvDfAptvmQmFoMwmDkiOi7cZOQTplccAjaue7gWQYDgCHXS25A3BIyPFadZU-laA6BCZtJ9JhZNnzPnGOaWWqeCwa2Vn4_3HnWtJMSZqK_vis
      rooms: 0b7b71f1-2140-433f-99d7-534d000f81c9

