apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
spec:
  schedule: "20 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gitea-backup
            env:
            - name: SSH_LISTEN_PORT
              value: "2222"
            - name: SSH_PORT
              value: "2222"
            - name: GITEA_APP_INI
              value: /data/gitea/conf/app.ini
            - name: GITEA_CUSTOM
              value: /data/gitea
            - name: GITEA_WORK_DIR
              value: /data
            - name: GITEA_TEMP
              value: /tmp/gitea
            - name: TMPDIR
              value: /tmp/gitea
            image: gitea/gitea:1.16.8-rootless
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - gitea dump -c /data/gitea/conf/app.ini
            volumeMounts:
            - mountPath: /data
              readOnly: true
              name: data
            - mountPath: /tmp
              name: data-gitea-backup
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-gitea-0
            - name: data-gitea-backup
              persistentVolumeClaim:
                claimName: data-gitea-0-backup

