global:
  networkPolicy:
    create: true

configs:
  ssh:
    extraHosts: |
      [gitea.sh4ke.rocks]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRCQpuNNyqfjPxBtYKX3BLN3oGdL5Tm5BjyFKpBk6e7AbF5z/azZAWyBQKAufyjkvvC+TNmdqkLc1qG5feCs81UBFAgXmK3xYAuaJNAzbf3TP0NGgLD+gtzPm1ZEXy0lGN7pdfGm9e1GFDLDbvimijCPxbScnpnCGUHzT8CqdZVznxgzbaBlyMfq9SXk+HFL8uVxwJWI3h3PHe/KRXlnSrUtMpW/AXP/cD9NFZb+cE891as8ZNewz+Sx3a8SH1dMbXktqZxyY4hbIBZt1NABGHov/AzXsUWQ/+e2j1hh5C9fd6mIKGfgYGtoW8CdVd2YQIjNvYYIE5e7wJUNnfCmuzRTIDVbw7Iu62TQ1LXBvnDCLf/TloEGVTk6yiFrgmfw7qF5kaZQ74vdUg5cZGZAAoMW07ohgcA9RNV2XerDgi9wGR+75Y5qfJAnQCAZdQ9U7bW0bPWiK1Uq5zht3rfSKgnAmZ9KnxFbTcTQYnAHYKkQ1rmsF5uUmEc9oEyc2zJlC0PJutIh/7CHu655gweklqKlm6zZRU1UDeiefKwX62ANVS1qE28Xphw7yeqaAgsO56q09LOLO7TNkhxfH2FPOyuiNna88Bu7dj7yfabVrYzZ3+/XqNgjb2+csrlPh8WOiTFhgQa1gz79T/iMmGr/5RL+wK5Kipd5K3Rm8kOO3rIw==
      [gitea.os.sh4ke.rocks]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRCQpuNNyqfjPxBtYKX3BLN3oGdL5Tm5BjyFKpBk6e7AbF5z/azZAWyBQKAufyjkvvC+TNmdqkLc1qG5feCs81UBFAgXmK3xYAuaJNAzbf3TP0NGgLD+gtzPm1ZEXy0lGN7pdfGm9e1GFDLDbvimijCPxbScnpnCGUHzT8CqdZVznxgzbaBlyMfq9SXk+HFL8uVxwJWI3h3PHe/KRXlnSrUtMpW/AXP/cD9NFZb+cE891as8ZNewz+Sx3a8SH1dMbXktqZxyY4hbIBZt1NABGHov/AzXsUWQ/+e2j1hh5C9fd6mIKGfgYGtoW8CdVd2YQIjNvYYIE5e7wJUNnfCmuzRTIDVbw7Iu62TQ1LXBvnDCLf/TloEGVTk6yiFrgmfw7qF5kaZQ74vdUg5cZGZAAoMW07ohgcA9RNV2XerDgi9wGR+75Y5qfJAnQCAZdQ9U7bW0bPWiK1Uq5zht3rfSKgnAmZ9KnxFbTcTQYnAHYKkQ1rmsF5uUmEc9oEyc2zJlC0PJutIh/7CHu655gweklqKlm6zZRU1UDeiefKwX62ANVS1qE28Xphw7yeqaAgsO56q09LOLO7TNkhxfH2FPOyuiNna88Bu7dj7yfabVrYzZ3+/XqNgjb2+csrlPh8WOiTFhgQa1gz79T/iMmGr/5RL+wK5Kipd5K3Rm8kOO3rIw==
      [gitea.ws.sh4ke.rocks]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDRCQpuNNyqfjPxBtYKX3BLN3oGdL5Tm5BjyFKpBk6e7AbF5z/azZAWyBQKAufyjkvvC+TNmdqkLc1qG5feCs81UBFAgXmK3xYAuaJNAzbf3TP0NGgLD+gtzPm1ZEXy0lGN7pdfGm9e1GFDLDbvimijCPxbScnpnCGUHzT8CqdZVznxgzbaBlyMfq9SXk+HFL8uVxwJWI3h3PHe/KRXlnSrUtMpW/AXP/cD9NFZb+cE891as8ZNewz+Sx3a8SH1dMbXktqZxyY4hbIBZt1NABGHov/AzXsUWQ/+e2j1hh5C9fd6mIKGfgYGtoW8CdVd2YQIjNvYYIE5e7wJUNnfCmuzRTIDVbw7Iu62TQ1LXBvnDCLf/TloEGVTk6yiFrgmfw7qF5kaZQ74vdUg5cZGZAAoMW07ohgcA9RNV2XerDgi9wGR+75Y5qfJAnQCAZdQ9U7bW0bPWiK1Uq5zht3rfSKgnAmZ9KnxFbTcTQYnAHYKkQ1rmsF5uUmEc9oEyc2zJlC0PJutIh/7CHu655gweklqKlm6zZRU1UDeiefKwX62ANVS1qE28Xphw7yeqaAgsO56q09LOLO7TNkhxfH2FPOyuiNna88Bu7dj7yfabVrYzZ3+/XqNgjb2+csrlPh8WOiTFhgQa1gz79T/iMmGr/5RL+wK5Kipd5K3Rm8kOO3rIw==

server:
  configEnabled: true
  ingress:
    enabled: true
    https: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingressClassName: nginx
    hosts:
      - argocd.os.sh4ke.rocks
    tls:
      - secretName: argocd-os-sh4ke-rocks-tls
        hosts:
          - argocd.os.sh4ke.rocks
  config:
    kustomize.path.default: /usr/local/bin/kustomize
    sshConfigs: |
      Host gitea.sh4ke.rocks
          KexAlgorithms ecdh-sha2-nistp521
          PubkeyAcceptedAlgorithms +ssh-rsa
      Host gitea.os.sh4ke.rocks
          KexAlgorithms ecdh-sha2-nistp521
          PubkeyAcceptedAlgorithms +ssh-rsa
      Host gitea.ws.sh4ke.rocks
          KexAlgorithms ecdh-sha2-nistp521
          PubkeyAcceptedAlgorithms +ssh-rsa

repoServer:
  envFrom:
    - secretRef:
        name: argocd-vault-plugin-credentials
  volumeMounts:
    - name: ssh-configs
      mountPath: /home/argocd/.ssh/
  extraContainers:
    - name: avp-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: sh4ke/argocd-plugins
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
        - mountPath: /home/argocd/cmp-server/config/
          name: cmp-plugin-avp-helm
        - mountPath: /tmp
          name: cmp-plugin-avp-helm-tmp
    - name: avp-helm-kustomize
      command: [/var/run/argocd/argocd-cmp-server]
      image: sh4ke/argocd-plugins
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
        - mountPath: /home/argocd/cmp-server/config/
          name: cmp-plugin-avp-helm-kustomize
        - mountPath: /tmp
          name: cmp-plugin-avp-helm-kustomize-tmp
    - name: kustomize-build-with-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: sh4ke/argocd-plugins
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        # Remove this volumeMount if you've chosen to bake the config file into the sidecar image.
        - mountPath: /home/argocd/cmp-server/config/
          name: kustomize-build-with-helm
        - mountPath: /tmp
          name: kustomize-build-with-helm-tmp
  volumes:
    - name: cmp-plugin-avp-helm
      configMap:
        name: cmp-plugin-avp-helm
    - name: cmp-plugin-avp-helm-kustomize
      configMap:
        name: cmp-plugin-avp-helm-kustomize
    - name: kustomize-build-with-helm
      configMap:
        name: kustomize-build-with-helm
    - name: cmp-plugin-avp-helm-tmp
      emptyDir: {}
    - name: cmp-plugin-avp-helm-kustomize-tmp
      emptyDir: {}
    - name: kustomize-build-with-helm-tmp
      emptyDir: {}
    - name: ssh-configs
      configMap:
        name: argocd-cm
        items:
          - key: sshConfigs
            path: config
