apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Sh4kE/k8s-projects.git'
    path: privatebin/prod
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: privatebin
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
