name: Yaml Lint
on: [push]
jobs:
  lintAllTheCharts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.10.0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        check-latest: true

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.3.1

    # - name: Run chart-testing (list-changed)
    #   id: list-changed
    #   run: |
    #     changed=$(ct list-changed)
    #     if [[ -n "$changed" ]]; then
    #       echo "::set-output name=changed::true"
    #     fi

    - name: Run chart-testing (lint)
      run: ct lint
